name: Deploy to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ssh-agent
        run: eval $(ssh-agent -s)

      - name: Add SSH private key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Deploy code to EC2 instance
        run: |
          sudo rsync -r --delete-after ${{ github.workspace }}/ /var/www/html/
          ssh ubuntu@15.206.122.146 'sudo chown -R www-data:www-data /var/www/html'
