name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH key
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add SSH key to agent
        run: ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: 13.127.190.236
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html
            sudo rm -rf *
            sudo git clone https://github.com/Devmoweb/clientwebsite.git .
      - name: Verify deployment
        run: |
          curl http://13.127.190.236
